jamesramsay/hercule

- lib/transclude.js
- package.json
- src/transclude.coffee
- test/index.coffee
- test/index.js
- Fixes issue where EOF line breaks and new line (`\n `) cause unexpected paragraphs and breaks (closes #9)
> Para breaks

- .travis.yml
- package.json
- src/main.coffee
> Moved blanket to dependency

- README.md
> Fixed readme library example

- .travis.yml
- README.md
- package.json
- src/grammar.coffee
- src/hercule.coffee
- src/main.coffee
- src/utils.coffee
- test/bats
- test/fixtures/test-basic/jackdaw.md
- test/fixtures/test-http-live/jackdaw.md
- test/fixtures/test-http/jackdaw.md
- test/hercule.coffee
- test/utils.coffee
Added basic support for remote files. Based on work by @MichaelHirn in #30.
> Support for remote file (HTTP) links

- .gitignore
- .travis.yml
Per: http://docs.travis-ci.com/user/migrating-from-legacy
> Removed sudo to support Travis container-based infrastructure requirements

- .travis.yml
- package.json
- scripts/install-bats
- Cache `node_modules`
- Cache `test/modules` which contains `bats` for CLI testing
> Travis config improvements for performance

- package.json
- src/transclude.pegjs
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
> Updated pegjs to version 0.9.0

- package.json
Pinned deps was stupid. Too much PR chatter for no reason.
> Unpin dependencies

- package.json
- src/regex-stream.js
- test/regex-stream.js
- Split stream into chunks that are matching or non-matching
> Regex stream

- package.json
- src/peg-stream.js
- src/transclude.pegjs
- test/peg-stream.js
- Parses objects with expressions, otherwise skips
> pegjs stream

- src/resolve-stream.js
- test/resolve-stream.js
- Resolves transclusion links to final link to be processed.
> Transclusion link resolving stream

- .eslintrc
- package.json
- src/inflate-stream.js
- src/main.js
- src/peg-stream.js
- src/regex-stream.js
- src/resolve-stream.js
- test/inflate-stream.js
- test/peg-stream.js
- test/regex-stream.js
- test/resolve-stream.js
Enable eslint to ensure consistent code style.
> Enable eslint (airbnb/legacy rules for ES5)

- src/config.js
- src/regex-stream.js
- test/regex-stream.js
> Added failing real world regex test

- package.json
- src/hercule.coffee
- test/transcludeFileSync.js
@dgileadi could you take a look and let me know if this solves for your use case (#93)?
As you suggested, this could probably be refactored into the existing function signature if no callback is provided.
Implemented new function signature for simplicity, but will look at a simpler public API in version 2.
> transcludeFileSync (Sync API)

- src/config.js
- src/hercule.js
- src/indent-stream.js
- src/inflate-stream.js
- src/regex-stream.js
- src/resolve-stream.js
- src/transclude-stream.js
- src/trim-stream.js
- test/regex-stream.js
Was using ES5 style `module.exports` rather than ES2015 style.
> chore(es2015): use ES2015 exports

- package.json
- src/transclude-stream.js
Use through2 to provide the same functionality.
> Update: remove event-stream dependency (fixes #123)

- CONTRIBUTING.md
- scripts/init
> Docs: init script (closes #132)

- .travis.yml
See https://github.com/npm/npm/issues/11283
> Build: disable npm progress bar for increased performance

- package.json
> chore(package): update ava to version 0.11.0

- src/main.js
This may be considered a breaking change, or perhaps even a fix if you consider the old behaviour wrong. If you want the commit tag changed let me know and I will gladly update it.
> Update: Errors now logged to stderr (fixes: #250)

- package.json
> Upgrade: eslint-config-airbnb-base to version 5.0.0

- README.md
- package.json
- src/resolver.js
- test/fixtures/references/_expect.md
- test/fixtures/references/_expect.md.map
- test/fixtures/references/index.md
- test/fixtures/references/venues.md
RegExp was not enforcing protocol as the first character of the string.
> Fix: http link detection

- .eslintrc.json
- README.md
- package.json
- src/grammar/index.js
- src/hercule.js
- src/main.js
- src/parse.js
- src/resolver.js
- src/sourcemap.js
- src/transclude.js
- src/trim.js
- test/.eslintrc.json
- test/benchmark.js
- test/fixtures/index.js
- test/integration/_mock.js
- test/integration/_transcludeFile.js
- test/integration/_transcludeString.js
- test/integration/transcludeStream.js
- test/units/grammar.js
- test/units/indent.js
- test/units/resolver.js
- test/units/sourcemap.js
- test/units/transclude.js
- test/units/transcludeFile.js
- test/units/transcludeStream.js
- test/units/transcludeString.js
- test/units/trim.js
- yarn.lock
Add precommit hook to make committed files prettier
Update all files to be consistent with prettier
> Build: use prettier

- .npmignore
Cruft has made it into the published npm package. 🔥 🔥 🔥
> Build: cleanup deploy artifact

- .npmignore
- .travis.yml
- Dockerfile
Use Travis to deploy docker images to Docker registry rather than using Docker Cloud.
> Update: tagged docker images

- README.md
Improve the documentation of syntax and make initial focus usage rather than the API.
Closes #394 
Closes #234
> Improved documentation clarity

- .travis.yml
Now that node 8 is LTS, this should be tested
> test: include node 8

- package.json
- yarn.lock
Fixes typicode/husky#144 which occurred on my machine.
> Update husky to 0.14.3

- .prettierrc.json
- package.json
- src/hercule.js
- src/main.js
- src/transclude.js
- test/units/transclude.js
- yarn.lock
Adds support for config files which are more friendly for integrations with editors.
> fix(package): update prettier to version 1.8.0

- src/hercule.js
> refactor: Define static arguments in variadic functions

- package.json
FYI  @realityking - I think this should be the final fix :)
> Fix typo causing missing promises.js
