src/hercule.coffee, test/fixtures/test-extend/activity.md, test/fixtures/test-extend/fox.md
Fixed issue where empty extends (`:[empty extend link](file.md extend:"")` and :[empty extend link](file.md extend:)) would fail.
=> Fix empty reference extension

src/grammar.coffee, src/hercule.coffee, test/fixtures/test-default/attribute-file.md, test/fixtures/test-default/invalid-link.md, test/fixtures/test-default/undefined-placeholder.md, test/hercule.coffee, test/utils.coffee
Based on #40 
Adds new syntax for default values:
```markdown
:[Placeholder link example](placeholder || "default if placeholder isn't provided")
:[Missing file example](example.md || "default if example.md can't be found")
```
This is useful for handling optional overrides or dynamically generated files that might not exist.
/cc @MichaelHirn
=> Support for default values

src/hercule.coffee, test/fixtures/test-default/missing-link.md, test/hercule.coffee
The current code fails to call `done()` if a transcluded file couldn't be found. It should simply fail to make the replacement and continue processing.
=> Don't hang if a transclusion couldn't be found

src/hercule.coffee, test/fixtures/special-characters/_expect.md, test/fixtures/special-characters/bar.md, test/fixtures/special-characters/foo.md, test/fixtures/special-characters/index.md
- str.replace supports special patterns which cannot be guaranteed to
not to occur in input files.
- Changed use of replace to use a function to bypass special behaviour
Thanks to @dgileadi for the bug report #64 :rocket:
=> Fixed handling of special characters

src/hercule.coffee, test/fixtures/reset-references/_expect.md, test/fixtures/reset-references/index.md, test/fixtures/reset-references/required.md
As the test shows, if multiple includes resolve to the same file and if one of the includes has a reference, that reference will be propagated to all the subsequent includes, even to those that don't specify the reference.
The culprit is the fact that loadash's `merge` function modifies its first argument rather than returning a brand new clone. The solution is to merge everything into an empty array, to avoid accidentally modifying `parentRefs`.
Another possible solution might be the code
references = _.merge references, parentRefs
But that would override any same-named references in `references` with those in `parentRefs`, which would probably be undesirable.
=> Don't preserve resolved references for siblings

.babelrc, package.json
- Use `compile` environment to avoid `.babelrc` messing with ava's own version of babel.
=> Enable Babel ES2015 transcompiler

src/trim-stream.js, test/trim-stream.js
- Transcluding a file in line without striping the trailing new line
results in the output having extra new lines which are not desired.
=> Strip trailing new line at EOF for nested transcludes

src/resolve-stream.js, test/resolve-stream.js
Only references from parent links should influence how the link is resolved,
not references within the link that is being resolved.
=> fix(resolve-stream): handling of parentRefs

src/main.js, test/inflate-stream.js
Disable two console.log lint warnings required for CLI feedback when help should be rendered.
=> Fix neccessary console.log lint warnings

package.json, scripts/coverage
Tests were being run twice. Once to determine test pass/fail, and again for calculating coverage. The results of the first test are sufficient to calculate coverage.
=> chore(coverage): prevent running tests twice

src/inflate-stream.js, src/peg-stream.js, src/transclude-stream.js, test/fixtures/syntax-error/_expect.md, test/fixtures/syntax-error/index.md, test/peg-stream.js
If the transclusion link is malformed, pegjs will be unable to parse the link an will throw an exception.
This should be handled by stopping the link from being processed further, and output should contain unmodified link.
Closes #107
=> fix(peg-stream): catch pegjs parsing errors preventing program crash

src/hercule.coffee, src/utils.coffee, test/inflate.js, test/read.js, test/transcludeString.js
The current code offers the ability to provide a custom logger for debug messages, but offers no customization for error logging (which can happen due to file-not-found errors or HTTP errors). This pull request adds support for making the logger argument be an object with `debug` and `error` functions. If no logger argument is provided or if the logger argument is a function then the current behavior is used.
=> Support a custom logger for errors

package.json
2.x.x releases should be on the `next` dist-tag to prevent new users accidentally ending up on 2.x release.
=> chore(npm): 2.x.x-alpha should be on the `next` dist-tag

src/config.js, src/inflate-stream.js, src/regex-stream.js, src/transclude-stream.js, test/regex-stream.js
- Fix issue where chunk.content also included indent. If resolve or
inflate failed, extra white space would be added before the link.
- Refactored config for regex-stream.
=> fix(indent): leave behind indentation assumed no failures

CONTRIBUTING.md, package.json, scripts/commit-msg
Uses ESLint commit style: http://eslint.org/docs/developer-guide/contributing/pull-requests#step2
Previously had been using the angular commit style for v2. In practice it feels more cumbersome than the ESLint style, and given the much smaller project size, the advantages of the angular style are outweighed.
=> Build: add commit-msg validation (refs #95)

.babelrc, package.json, test/units/indent-stream.js, test/units/inflate-stream.js, test/units/regex-stream.js, test/units/resolve-stream.js, test/units/trim-stream.js
- Breaking change to handling of nested tests. Unit and integration tests
are now in separate non-nested directories.
- Babel 6 is now being used by ava removing the need for .babelrc to be
scoped to compile time
=> Update: ava 0.9.1

scripts/commit-msg
- Allow `chore(upgrade)` commit message
- Allow upgrade commits to skip providing an issue reference
=> Build: permit greenkeeper `chore(upgrade)` commit style (fixes #161)

src/hercule.js, src/main.js, test/bats, test/integration/transcludeFileSync.js, test/integration/transcludeStringSync.js, test/units/transcludeFile.js, test/units/transcludeFileSync.js, test/units/transcludeString.js, test/units/transcludeStringSync.js
**BREAKING:** CLI argument `relative` renamed to `relativePath`
=> Fix: sync API incorrectly required `relativePath` option (fixes #178)

src/hercule.js, src/inflate-stream.js, src/resolve-stream.js, src/transclude-stream.js, test/units/transcludeFile.js, test/units/transcludeString.js
Retrieving the list of all paths included in the output file is useful for live reload applications where all the source files must be watched to trigger regeneration of the output and an update watch list.
=> New: ability to pass in pathList variable (closes #196)

src/hercule.js, src/main.js, test/fixtures/invalid-link/_expect.json, test/fixtures/invalid-link/_expect.md, test/fixtures/invalid-link/index.md, test/integration/transcludeFile.js, test/integration/transcludeString.js, test/units/transcludeFile.js, test/units/transcludeString.js
`process.exit()` wasn't being called on first error when being executed through sync API.
=> Fix: sync API exception when multiple errors thrown (fixes #219)

README.md, src/hercule.js, src/inflate-stream.js, src/resolve-stream.js, src/transclude-stream.js, test/units/transcludeFile.js, test/units/transcludeString.js
Accessing the pathList by providing an error is very hackish and fragile approach.
Implementation has been updated to emit `sources` event from the core transclusion stream which is then captured and provided as an argument to the callback.
=> Improved API for accessing sourceFilePaths

package.json, src/hercule.js, src/inflaters/string.js, src/main.js, src/resolve-stream.js, src/resolve.js, src/transclude-stream.js, src/trim-stream.js, test/integration/transcludeStream.js, test/units/inflaters/string.js, test/units/resolve-stream.js, test/units/resolve/parseLink.js, test/units/resolve/parseTransclude.js, test/units/trim-stream.js
This allows reference sources to easily be propagated for use in sourcemaps.
=> Update: string inflater returns an object rather than a text stream.

src/inflaters/http.js, src/inflaters/local.js, src/resolve-stream.js, src/trim-stream.js, test/units/inflaters/http.js, test/units/inflaters/local.js, test/units/resolve-stream.js, test/units/trim-stream.js
Improves isolation of logic associated with transcluding files in contrast with strings.
TODO: add tests for HTTP and Local inflaters
=> Update: refactor inflaters to handle trimming

src/indent-stream.js, test/fixtures/indentation/_expect.md, test/fixtures/indentation/_expect.md.map, test/fixtures/indentation/index.md, test/units/indent-stream.js
Indentation (whitespace) should never be inserted between two new lines (`\n\n`) nor on the final line of output (`\n___`).
Closes #334
=> Fix: indentation regression

examples/gulp/gulpfile.js
The `hercule.transcludeString` and `hercule.TranscludeStream` functions were throwing errors when running the basic gulp example, but after updating their signatures everything worked great.
=> Update gulp example

Dockerfile
It'd be great if this tool was available as a Docker container.  Depending on the npm release process, `@latest` may not be the best route.  DockerHub builds can be configured to initiate a build whenever a new `tag` or release is added to the repo.
=> Add official Docker support

CHANGELOG.md, README.md, src/resolver.js, src/transclude.js, test/units/resolver.js
The placeholder argument allows resolvers that pass the entire link straight through rather than consuming it.
Closes #386 
Closes #389
=> Add placeholder arg to resolver API

.travis.yml
Deploy steps should never be trigger on branches other than master.
=> build: only deploy from master branch

src/main.js
I discovered it doesn't actually work while trying to update meow to version 4.
To confirm add the following test case to `test/bats`:
```
@test "accepts input from stdin using shorthand" {
run bash -c "cat ./test/fixtures/local-link/index.md | ./bin/hercule - --relative ./test/fixtures/local-link"
[ "$status" -eq 0 ]
[ "$output" == "Jackdaws love my big sphinx of quartz." ]
}
```
=> fix(cli): Remove mention of - as a shorthand for --stdin

package-lock.json, package.json
Multiple versions of through2 are no longer required.
Only through2@4.0.2 is required.
=> Upgrade through2-get and through2

README.md, package.json, promises.js, src/promises.js, test/units/transcludeFilePromises.js, test/units/transcludeStringPromises.js
Fixes #442
This is especially valuable for Hercule because a standard `promisify` loses access to the source map.
This matches the pattern that Node.js is adopting (e.g. `fs/promises`) and gives a clean separation between the promise based and the callback interface. If you ever want to change the default you could introduce `hercule/callback` and the migration strategy would be to simply change the import.
Note that the use of `exports` will prevent deep-requiring anything files shipped in the package. For example `require('hercule/lib/parse.js')` would no longer work. This could be considered a breaking change. I did add `package.json` to the list of exported files as some tools require access to it (see https://github.com/nodejs/node/issues/33460).
=> Add a promise based API available as "hercule/promises"

.eslintrc.json, src/hercule.js, src/indent.js, src/parse.js, src/resolver.js, src/sourcemap.js, src/transclude.js, src/trim.js, test/integration/transcludeFile.js, test/integration/transcludeStream.js, test/integration/transcludeString.js, test/units/resolver.js
Aligning with https://github.com/jamesramsay/through2-get/pull/118 this PR does two things
- Use the per-method imports for lodash 
- Make use of native Node.js functionality when that's easily possible
Use Node.js 14.15.1 the benchmark results show no performance impact or even a tiny improvement:
main:
```
> ./test/benchmark.js
hercule#transcludeFile x 1,284 ops/sec ±6.85% (71 runs sampled)
hercule#TranscludeStream x 1,525 ops/sec ±0.79% (82 runs sampled)
hercule#transcludeString x 1,616 ops/sec ±0.68% (85 runs sampled)
```
This branch:
```
> ./test/benchmark.js
hercule#transcludeFile x 1,309 ops/sec ±8.13% (71 runs sampled)
hercule#TranscludeStream x 1,543 ops/sec ±0.93% (79 runs sampled)
hercule#transcludeString x 1,639 ops/sec ±1.25% (82 runs sampled)
```
Outside of tests the …
=> Reduce reliance on lodash methods

package.json
There are two missing files in 5.1:
1. `grammar/link.js`
2. `promises.js`
1. is because I made a typo in #599 (🤦). 2. is because #603 was created before #599 was merged so it couldn't add the new file to the list.
Sorry for the extra pain.
=> Fix: package did not include all required files
